from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
# 依赖: attitude_so3 (mixer_cmd 取内环输出) / param_calib (calib_parse_num)
CPPPATH = [cwd, GetCurrentDir() + '/../../Control/attitude_so3']

group = DefineGroup('ControlAlloc', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
