from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
# 传感器驱动层: ADIS 驱动 DR EXTI ISR 内捕获 T_MCU 时戳 (middleware/timebase)
CPPPATH = [cwd, cwd + '/../timebase']

group = DefineGroup('Sensors', src, depend = ['RT_USING_SENSOR'], CPPPATH = CPPPATH)

Return('group')
