from building import *

cwd = GetCurrentDir()

# 传感器校准中间件: ellipsoid_fit(纯数学) + mag_calib(磁力计椭球)
#                  + baro_calib(气压计偏移); 持久化已迁 middleware/param_calib
#                  (W25Q64 calib 分区, calib_store_* API 原样保留)
src = Glob('*.c')
CPPPATH = [cwd, cwd + '/../timebase', cwd + '/../param_calib']

group = DefineGroup('Calibration', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
